name: CI
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build:
    env:
      sshkey: ${{ secrets.SSH_PRIVATE_KEY }}
      sshuser: ${{ secrets.SSH_USER }}
      sship: ${{ secrets.SSH_IP }}
      sshknownhost: ${{ secrets.SSH_KNOWN_HOST }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: mkdir -p ~/.ssh/
    - run: ls
    - run: ls ~/.ssh
    - run: echo $sshknownhost > ~/.ssh/known_hosts
    - run: cat ~/.ssh/known_hosts
    - run: echo $sshkey > ./file.txt && chmod 600 ./file.txt
    - run: ssh $sshuser@$sship -i ./file.txt "ls -la"
